 pipeline {
    agent any

    tools {
        nodejs "NodeJS18"
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('vtiger_crm_framework_playwright') {
                    bat 'npm install'
                    bat 'npx playwright install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('vtiger_crm_framework_playwright') {
                    bat 'npx playwright test'
                }
            }
        }
    }
}